import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Importing the Toaster component from the shadcn components library for showing toasts.
import { Toaster } from "@/components/ui/toaster";

// Importing the AuthProvider for wrapping the children components with SessionProvider.
import AuthProvider from "@/context/AuthProvider";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Wrapping the whole body as children with AuthProvider. */}
      <AuthProvider>
        <body className={inter.className}>
          {/* <Navbar /> */}
          {children}
          {/* Rendering the Toaster component inside body for showing toasts. */}
          <Toaster />
        </body>
      </AuthProvider>
    </html>
  );
}
